controller_list:
  - name: fake_manipulator_controller
    joints:
      - rail_y
      - robot_joint_s
      - robot_joint_l
      - robot_joint_e
      - robot_joint_u
      - robot_joint_r
      - robot_joint_b
      - robot_joint_t
  - name: fake_manipulator_camera_controller
    joints:
      - rail_y
      - robot_joint_s
      - robot_joint_l
      - robot_joint_e
      - robot_joint_u
      - robot_joint_r
      - robot_joint_b
      - robot_joint_t
  - name: fake_manipulator_gripper_controller
    joints:
      - rail_y
      - robot_joint_s
      - robot_joint_l
      - robot_joint_e
      - robot_joint_u
      - robot_joint_r
      - robot_joint_b
      - robot_joint_t