joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

arm_controller:
    type: position_controllers/JointTrajectoryController
    joints:
        - rail_y
        - robot_joint_b
        - robot_joint_e
        - robot_joint_l
        - robot_joint_r
        - robot_joint_s
        - robot_joint_t
        - robot_joint_u
    constraints:
        goal_time: 0.6
        stopped_velocity_tolerance: 0.05
        rail_y: {trajectory: 0.1, goal: 0.1}
        robot_joint_b: {trajectory: 0.1, goal: 0.1}
        robot_joint_e: {trajectory: 0.1, goal: 0.1}
        robot_joint_l: {trajectory: 0.1, goal: 0.1}
        robot_joint_r: {trajectory: 0.1, goal: 0.1}
        robot_joint_s: {trajectory: 0.1, goal: 0.1}
        robot_joint_t: {trajectory: 0.1, goal: 0.1}
        robot_joint_u: {trajectory: 0.1, goal: 0.1}
    stop_trajectory_duration: 0.5
    state_publish_rate: 25
    action_monitor_rate: 10
